config/routes.rb
Obxpi::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :articles do
    resources :comments
  end
  
  get "user_info", to: "users#info"
  get "user_gabloons_to_frammes", to: "users#gabloons_to_frammes"
  get "poison_pet/:id", to: "users#poison_pet", as: :poison_pet
  resources :users do
    resource :page
  end
  
  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  
  resources :links do
    get 'vote', on: :member
  end
  
  resources :shouts
  
  resources :money_transactions
  
  get "r/:tiny_url", to: "repos#download", as: :tiny_url_repo
  post "repos/s3_callback", to: "repos#s3_callback", as: :s3_callback_repo
  resources :repos do
    get "download", on: :member
  end
  
  get "market", to: "market#index"
  get "market/purchase/:id", to: "market#purchase", as: :market_purchase
  
  get "misc", to: "misc#index"
  post "shout", to: "misc#shout", as: :misc_shout
  
  get "admin", to: "admin#index"
  get "admin/:user_id/make", to: "admin#make", as: :make_admin
  get "admin/:user_id/remove", to: "admin#remove", as: :remove_admin
  get "admin/edit_user/:user_id", to: "admin#edit_user", as: :edit_user_admin
  patch "admin/update_user/:user_id", to: "admin#update_user", as: :update_user_admin
  
  get "u/:user_name", to: "pages#show", as: :u_page
  
  get "online_users", to: "home#online_users", as: :online_users
  get "activity_log", to: "home#activity_log"
  get "stream", to: "home#stream"
  root to: "home#index"
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :body
  
  belongs_to :article
  belongs_to :user
  
  has_many :mentions, as: :mentionable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_filter :ensure_user_has_edits, only: [:edit, :update]
  
  def index
    @article = Article.find(article_id)
    @comments = @article.comments.order(created_at: :desc)
  end
  
  def create
    article = Article.find(article_id)
    comment = article.comments.new(comment_params)
    comment.user = current_user
    if comment.save
      Mention.generate(comment)
      ActivityLog.log('comment', comment.id, current_user)
      current_user.give_gabloons(2)
      flash[:notice] = "Your reply is appreciated, probably."
    else
      flash[:notice] = "Your reply was not saved. Ha."
    end
    redirect_to article_comments_path(article)
  end
  
  def edit
    @comment = Comment.find(comment_id)
  end
  
  def update
    comment = Comment.find(comment_id)
    if comment.update_attributes(comment_params)
      Mention.generate(comment)
      current_user.take_edit!
    end
    redirect_to article_comments_path(comment.article)
  end
  
  private
  
  def comment_id
    params[:id]
  end
  
  def article_id
    params[:article_id]
  end
  
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_for [@comment.article, @comment] do |f| %>
  <%= f.text_area :body %>
  <%= f.submit "Update" %>
<% end %>

app/views/comments/index.html.erb
<div id="news">
  <div class="news-item">
    <h2><%= @article.title %></h2>
    
    <div class="news-item-info">
      <div class="avatar_wrap">
        <div class="avatar">
          <%= image_tag @article.user.avatar.url(:thumb) %> 
        </div>
      </div>
      <span class="user-name">by <%= link_to @article.user.name, user_path(@article.user) %></span>
      <span class="created-at">on <%= @article.created_at.strftime('%m/%d/%Y at %I:%M%p') %></span>
      <%= link_to "Edit", edit_article_path(@article) if user_has_edits? %>
    </div>

    <div class="news-content">
      <p><%= kramdown_format @article.blurp %></p>
    </div>
  </div>
  <div id="comments" class="comment-section">
    <% if user_signed_in? %>
      <h2 class="comment-header">Comments</h2>
      <%= form_for [@article, Comment.new] do |f| %>
        <%= f.text_area :body %>
        <%= f.submit "Post", class: 'comment-submit' %>
      <% end %>
    <% else %>
        <h2 class="comment-header">Comments <span>(Requires Login)</span></h2>
    <% end %>
    
    <% @comments.each do |comment| %>
    <div class="comment<%= cycle(" selected", "") %>">
      <div class="avatar_wrap">
        <div class="avatar">
          <%= image_tag comment.user.avatar.url(:thumb) %> 
        </div>
      </div>
      <%= format_and_link_user comment.user %>
      <span class="created-at">on <%= @article.created_at.strftime('%m/%d/%Y at %I:%M%p') %></span>
      -
      <%= format_model_body(comment) %>
      <%= link_to "Edit", edit_article_comment_path(comment.article, comment) if user_has_edits? %>
    </div>
    <% end %>
  </div>
</div>