config/routes.rb
Obxpi::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :articles do
    resources :comments
  end
  
  get "user_info", to: "users#info"
  get "user_gabloons_to_frammes", to: "users#gabloons_to_frammes"
  get "poison_pet/:id", to: "users#poison_pet", as: :poison_pet
  resources :users do
    resource :page
  end
  
  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  
  resources :links do
    get 'vote', on: :member
  end
  
  resources :shouts
  
  resources :money_transactions
  
  get "r/:tiny_url", to: "repos#download", as: :tiny_url_repo
  post "repos/s3_callback", to: "repos#s3_callback", as: :s3_callback_repo
  resources :repos do
    get "download", on: :member
  end
  
  get "market", to: "market#index"
  get "market/purchase/:id", to: "market#purchase", as: :market_purchase
  
  get "misc", to: "misc#index"
  post "shout", to: "misc#shout", as: :misc_shout
  
  get "admin", to: "admin#index"
  get "admin/:user_id/make", to: "admin#make", as: :make_admin
  get "admin/:user_id/remove", to: "admin#remove", as: :remove_admin
  get "admin/edit_user/:user_id", to: "admin#edit_user", as: :edit_user_admin
  patch "admin/update_user/:user_id", to: "admin#update_user", as: :update_user_admin
  
  get "u/:user_name", to: "pages#show", as: :u_page
  
  get "online_users", to: "home#online_users", as: :online_users
  get "activity_log", to: "home#activity_log"
  get "stream", to: "home#stream"
  root to: "home#index"
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates_presence_of :title, :blurp
  
  belongs_to :user
  
  has_many :comments
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_user?, except: [:edit, :update]
  before_filter :ensure_admin_or_editable, only: [:edit, :update]
  
  def index
    @articles = Article.order(created_at: :desc)
  end
  
  def new
    @article = Article.new
  end
  
  def create
    article = current_user.articles.new(article_params)
    if article.save
      redirect_to articles_path
    else
      render :new
    end
  end
  
  def edit
    @article = Article.find(article_id)
    render :new
  end
  
  def update
    article = Article.find(article_id)
    article.update_attributes(article_params)
    if current_user.admin?
      redirect_to articles_path
    else
      current_user.take_edit!
      redirect_to root_path
    end
  end
  
  def destroy
    article = current_user.articles.find(article_id)
    article.comments.each do |comment|
      comment.mentions.each do |mention|
        mention.destroy
      end
      comment.destroy
    end
    article.destroy
    redirect_to articles_path
  end
  
  private
  
  def ensure_admin_or_editable
    ensure_user_has_edits unless current_user.admin?
  end
  
  def article_params
    params.require(:article).permit(:title, :blurp)
  end
  
  def article_id
    params[:id]
  end
end

app/views/articles/index.html.erb
<%= link_to "Create Article", new_article_path %>

<div id="news">

    <% @articles.each do |article| %>
      <div class="news-item">
        <h2><%= article.title %></h2>
        <p><%= article.blurp %></p>
        <div class="news-item-footer">
          <%= link_to article.user.name, user_path(article.user) %>
          [<%= article.created_at.strftime('%m/%d/%Y at %I:%M%p') %>]
          <%= link_to "Delete", article_path(article), method: :delete %> |
          <%= link_to "Edit", edit_article_path(article) %>
        </div>
      </div>
    <% end %>
    
  </div>

app/views/articles/new.html.erb
<%= simple_form_for @article do |f| %>
  <%= f.input :title %>
  <%= f.input :blurp %>
  <%= f.button :submit %>
<% end %>