config/routes.rb
Obxpi::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  
  resources :articles do
    resources :comments
  end
  
  get "user_info", to: "users#info"
  get "user_gabloons_to_frammes", to: "users#gabloons_to_frammes"
  get "poison_pet/:id", to: "users#poison_pet", as: :poison_pet
  resources :users do
    resource :page
  end
  
  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  
  resources :links do
    get 'vote', on: :member
  end
  
  resources :shouts
  
  resources :money_transactions
  
  get "r/:tiny_url", to: "repos#download", as: :tiny_url_repo
  post "repos/s3_callback", to: "repos#s3_callback", as: :s3_callback_repo
  resources :repos do
    get "download", on: :member
  end
  
  get "market", to: "market#index"
  get "market/purchase/:id", to: "market#purchase", as: :market_purchase
  
  get "misc", to: "misc#index"
  post "shout", to: "misc#shout", as: :misc_shout
  
  get "admin", to: "admin#index"
  get "admin/:user_id/make", to: "admin#make", as: :make_admin
  get "admin/:user_id/remove", to: "admin#remove", as: :remove_admin
  get "admin/edit_user/:user_id", to: "admin#edit_user", as: :edit_user_admin
  patch "admin/update_user/:user_id", to: "admin#update_user", as: :update_user_admin
  
  get "u/:user_name", to: "pages#show", as: :u_page
  
  get "online_users", to: "home#online_users", as: :online_users
  get "activity_log", to: "home#activity_log"
  get "stream", to: "home#stream"
  root to: "home#index"
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_subdomain_for_user, only: [:index]
  
  def index
    @articles = Article.order(created_at: :desc).limit(7)
    @activity_log = ActivityLog.stream
  end
  
  def online_users
    @users = User.online
  end
  
  def activity_log
    @activity_log = ActivityLog.stream
    
    respond_to do |format|
      format.json
    end
  end
  
  def stream
    @activity_log = ActivityLog.stream
    render layout: 'stream'
  end
  
  private
  
  def check_subdomain_for_user
    subdomain = request.subdomains.first
    if subdomain =~ User::NAME_REGEX && (!User::ILLEGAL_NAMES.include?(subdomain))
      user = User.where('lower(name) = ?', subdomain).first
      if user && user.page
        @page = user.page.formatted_markdown
        @user = user
        @style = user.page.formatted_style
        render '/pages/show', layout: "user_page"
      end
    end
  end
  
end

app/views/home/index.html.erb
<div id="main-contain" class="with_stream">
  <div id="news">
    <% @articles.each do |article| %>
      <div class="news-item">
        <h2><%= article.title %></h2>
        <div class="news-item-info">
          <div class="avatar_wrap">
          <div class="avatar">
            <%= image_tag article.user.avatar.url(:thumb) %> 
          </div>
          </div>
          <div class="news-stats-wrap">
            <span class="user-name">by <%= format_and_link_user(article.user) %></span>
            <span class="created-at">on <%= article.created_at.strftime('%m/%d/%Y at %I:%M%p') %> | </span>
            <span class="comments"> <%= link_to pluralize(article.comments.count, "Comment"), article_comments_path(article) %></span>
            <%= link_to "Edit", edit_article_path(article) if user_has_edits? %>
          </div>
        </div>
        <div class="news-content">
          <%= kramdown_format article.blurp %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: "shared/recent_activity" %>

app/views/home/online_users.html.erb
<h2>Users</h2>
<p>
  The following users are currently online:
</p>
<% @users.each do |user| %>
<p><%= link_to user.name, user_path(user) %></p>
<% end %>
<p>
  you may also enjoy viewing <%= link_to "all the users", users_path %></li>
</p>

app/views/home/stream.html.erb
<div id="activity_stream">
  <% @activity_log.each do |activity_log| %>
    <div>
      <div class="avatar_wrap">
        <div class="avatar">
          <%= image_tag activity_log.user.avatar.url(:thumb) %> 
        </div>
      </div>
      <p>
        <%= format_activity_log(activity_log) %>
      </p>
    </div>

    <br />
  <% end %>
</div>

<script type="text/javascript">
$(function() {
  home = new Home();
  home.start();
});
</script>